### PR TITLE
Convert from Silex to Symfony 4 flex

### LINKED ISSUE #38: Migrate Silex to new Symfony component
Silex is now deprecated in favor of the new Symfony components.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #38 

This was a learning experience so this might not be what you had in mind. 

For instance, I didn't make it as a bundle which you could deploy in a separate Symfony App, that is (apparently) an option.

This just migrates the existing app to use the symfony-flex framework.

I also (not sure why) added a new environment variable `TRELLIS_SOURCE_DIR` which allows you to not provide a configuration file (so use the default settings) but easily point to your source files. I can remove it and stick with existing behaviour.

It still supports the `TRELLIS_CONFIG_DIR` environment variable. Though I wonder why reference a directory and not the file directly? That might have been something I did for some unknown reason.

I also haven't tried configuring this in Apache, I've just used the built in webserver.

Lastly, they say you should use `App` as the top level namespace, so I just removed the `Trellis\StaticLdp` namespaces. If you want them back its not hard to just add the directories and update the namespaces.

Just wanted to get it out of my hands.
You can test by:
1. pulling down this branch.
1. change into the directory.
1. running `composer install|update`
1. run `php bin/console server:start`  to get a server running using a `settings.yml` file in the top level directory (symfony uses the `config` directory so I move out of there to not confuse things)

### CODE REVIEW

**Comment by acoburn** [comment]
@whikloj you are amazing.

**Comment by whikloj** [comment]
Hmm I see you are defining the environment variable in Travis. So we can drop the `.env.test` file, only useful for running phpunit locally.

**Comment by whikloj** [comment]
Ok this appveyor failure is related to symfony environments. Locally I set the TRELLIS_CONFIG_DIR in my phpunit file. I can do that or if you can set it like you do for Travis then we should (huge "should") be okay.

**Comment by acoburn** [comment]
Build success!

I'll see what I can do about the jpeg image being output in the test code.

**Comment by acoburn** [comment]
@whikloj if you’re happy with where this stands, I’ll merge it; but if there’s more you’d like to add to this PR, let me know

**Comment by whikloj** [comment]
@acoburn I'm good, there is probably extraneous cruft of Symfony I didn't need to push up. But it won't hurt anything and we can remove it. I am going to look at doing the same work for the CLAW microservices, so once I am done those I should be a master at this stuff and can do a better clean up.

**Pull request merged**
